### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by zh0122** [zwliew/android_device_xiaomi_hm2014811-old#2]
Hi,

I clone your repo and built it with latest official cm-11.
The ROM has no sound, including call sound and ring.

please check it, thanks!

**Comment by zwliew** [comment]
Yes, the device tree is not ready yet. I have other commitments so it takes time to get the tree fully working.

**Comment by zh0122** [comment]
Thanks for your contribution. 
Could you reply here when you fix this issue?
Thanks~ :)

**Comment by zwliew** [comment]
Sure.

**Comment by balika011** [comment]
I'm working on to get it work in cm12.1. ;)

**Comment by zwliew** [comment]
Fixed

**Comment by balika011** [comment]
yeah, 15 days ago :D

**Comment by zwliew** [comment]
Sorry, I didn't get
